<h2>Welcome, $user$</h2>

<h3>Enter Your Addresses, With Amount of Times You Visit Each Respective Address Per Year,
    To Find The Distances To Them From Brookline, Ma</h3>

<section>
    <p>Example:</p>

    <p><em>Boston, MA : 200</br>
       New York, NY : 4</em></p>
</section>
<form action="/" method="post">
    <textarea id="addresses" name="addresses" style="display: block; width: 400px; height: 200px"></textarea>
    <input type="submit" value="Submit"/>
</form>
